export const TROLL_MESSAGES = [
  "Oops!",
  "Too shaky!",
  "Skill issue detected",
  "Try again butterfingers",
  "Not even close",
  "Are you even trying?",
  "My grandma has steadier hands",
  "Slippery!",
  "Nice try",
  "Nope.",
  "Glitch in the matrix?",
  "Lag?",
  "User error",
  "Access Denied",
  "Error 404: Win not found",
  "Buffering...",
  "Recalculating...",
  "Do not pass go",
  "Slippery when wet",
  "Hand sweat detected",
  "Physics engine crashed",
  "Keyboard not found",
  "Mouse disconnected",
  "Nice hustle though",
  "Almost... psych!",
  "Precise movement required",
  "Too fast!",
  "Too slow!",
  "Just give up",
  "Why are you doing this?",
  "Go touch grass",
  "Go cry to your mama",
  "Get better hands",
  "Is your mouse broken?",
  "Hardware limitation: YOU",
  "Embarrassing...",
  "Pathetic attempt",
  "Delete the game",
  "You lack the hardware",
  "Emotional damage?",
  "Have you tried winning?",
  "Stop shaking",
];

export const INTENSE_MESSAGES = [
  "NO.",
  "ABSOLUTELY NOT",
  "SYSTEM FAILURE",
  "CRITICAL ERROR",
  "STOP IT",
  "IMPOSSIBLE",
  "DONT YOU DARE",
  "SECURITY ALERT",
  "UNAUTHORIZED",
  "VIOLATION DETECTED",
  "NOPE NOPE NOPE",
  "GET AWAY",
  "I SAID NO",
];

export const VICTORY_MESSAGES = [
  "YOU ACTUALLY DID IT!?",
  "IMPOSSIBLE!",
  "HACKER DETECTED!",
  "GODLIKE PATIENCE!",
  "FINALLY!",
];

export const UPLOAD_TAUNTS = [
  "Wifi disconnected?",
  "My grandma clicks faster",
  "Packet loss detected (Skill issue)",
  "Buffering... forever",
  "Why did you let go?",
  "So close! (Not really)",
  "Upload failed: PEBKAC error",
  "Server is busy ignoring you",
  "Have you tried turning it off?",
  "File too large for your patience",
  "Connection reset by peer",
  "User ran out of willpower",
  "Bitrate dropped to 0",
  "You are not worthy",
  "Go scratch your head",
  "You must construct additional pylons",
  "Critical failure detected in user",
  "Try harder",
  "Weak signal (in your brain)",
];

export const EARLY_FAILURE_TAUNTS = [
  "That was pathetic.",
  "Less than 3? Delete the app.",
  "My goldfish has better aim.",
  "Are your hands broken?",
  "Why even bother?",
  "A flat line is not a tower.",
  "You tripped at the starting line.",
  "Failure is an option, apparently.",
  "Do you need a tutorial for gravity?",
  "Just sad.",
  "Even the ground is disappointed.",
  "Try opening your eyes next time.",
  "ERROR: User skill not found."
];

export const ZEN_MESSAGES = [
  "Breathe. Try again.",
  "Maybe less force next time.",
  "Gravity is not your friend.",
  "Patience is a virtue you lack.",
  "A tower built on sand...",
  "Let it go.",
  "Perfection is an illusion.",
  "Chaos is the only constant.",
  "Was that intentional?",
  "Physics doesn't care about your feelings.",
  "Just relax. You're failing anyway.",
  "Balance is a lie.",
  "The wind whispers 'loser'.",
  "Not very Zen of you.",
  "Your tower is as unstable as your life.",
  "Gravity 1, You 0.",
  "I've seen better stacking from a toddler.",
  "Perhaps you should try breathing harder?",
  "Balance is clearly not your forte.",
  "A stiff breeze could have done better.",
  "That was embarrassing to watch.",
  "Are you trembling? I sense trembling.",
  "Physics isn't hard, but apparently it is for you.",
  "Your ancestors are weeping at this attempt.",
  "Maybe stick to stacking paper?",
  "Utter collapse. Just like your hopes.",
  "Namaste? More like Na-mess-stay.",
  "Inner peace not found. Only rubble.",
  "Zen master says: You suck.",
  "The universe rejects your tower.",
  "Meditate on your failure.",
  "A spectacular display of incompetence.",
  "You bring shame to the monastery.",
  "Is this your first time using hands?",
  "Even a rock sits still better than this."
];

export const COLORS = {
  primary: '#FF6B6B', // Redish
  secondary: '#4ECDC4', // Teal
  accent: '#FFE66D', // Yellow
  dark: '#292F36',
  light: '#F7FFF7',
};

export enum GameState {
  MENU = 'MENU',
  PLAYING_SLIDER = 'PLAYING_SLIDER',
  PLAYING_UPLOAD = 'PLAYING_UPLOAD',
  PLAYING_ZEN = 'PLAYING_ZEN',
  PLAYING_STAR = 'PLAYING_STAR',
  WON = 'WON',
}